SET curdir=%~dp0
rmdir /s /q "%curdir%obj"
rmdir /s /q "%curdir%binmodules\example\obj"
rmdir /s /q "%curdir%binmodules\luasocket\obj"
rmdir /s /q "%curdir%contrib\curl\bin"
rmdir /s /q "%curdir%contrib\curl\obj"
rmdir /s /q "%curdir%contrib\libzip\obj"
rmdir /s /q "%curdir%contrib\libzip\bin"
rmdir /s /q "%curdir%contrib\lua\obj"
rmdir /s /q "%curdir%contrib\lua\bin"
rmdir /s /q "%curdir%contrib\luashim\obj"
rmdir /s /q "%curdir%contrib\luashim\bin"
rmdir /s /q "%curdir%contrib\mbedtls\obj"
rmdir /s /q "%curdir%contrib\mbedtls\bin"
rmdir /s /q "%curdir%contrib\zlib\obj"
rmdir /s /q "%curdir%contrib\zlib\bin"